services:
  postgres:
    image: postgres:17-alpine
    container_name: outbox-transactional-db
    environment:
      POSTGRES_USER: outbox
      POSTGRES_PASSWORD: outbox
      POSTGRES_DB: outbox
    ports:
      - '5445:5432'
    volumes:
      - outbox_pgdata:/var/lib/postgresql/data

  pulsar:
    image: apachepulsar/pulsar:4.1.0
    container_name: outbox-transactional-pulsar
    command: bin/pulsar standalone
    ports:
      - '6650:6650'
      - '8080:8080'
    healthcheck:
      test:
        ['CMD-SHELL', 'curl sf http://localhost:8080/admin/v2/brokers/health']
      interval: 5s
      timeout: 5s
      retries: 30

volumes:
  outbox_pgdata: